
LoadPlugin("C:\Users\covec\Videos\vhs\software\Windows\FFmpeg-QTGMC Easy 2025.01.11/ffms2.dll")
FFmpegSource2("C:\Users\covec\Videos\vhs\tmp\vhs_tuner_extracts\callahan_01_archive__1995_jim_linda_wedding_13_reception_speech_march_18_1995__37541_38762__clean\extracted.mkv", atrack=-1)
chapter_start_frame = 37541
chapter_end_frame = 38762
c = last
c = c.FreezeFrame(22,22,25)
c = c.FreezeFrame(29,30,32)
c = c.FreezeFrame(130,139,141)
c = c.FreezeFrame(162,180,182)
c

