
LoadPlugin("C:\Users\covec\Videos\vhs\software\Windows\FFmpeg-QTGMC Easy 2025.01.11/ffms2.dll")
FFmpegSource2("C:\Users\covec\Videos\vhs\tmp\vhs_tuner_extracts\callahan_01_archive__1995_jim_linda_wedding_11_reception_ambiance_march_18_1995__32220_34075__clean\extracted.mkv", atrack=-1)
chapter_start_frame = 32220
chapter_end_frame = 34075
c = last
c = c.FreezeFrame(214,215,225)
c = c.FreezeFrame(218,219,225)
c = c.FreezeFrame(222,223,225)
c = c.FreezeFrame(239,245,247)
c = c.FreezeFrame(274,285,293)
c = c.FreezeFrame(288,291,293)
c = c.FreezeFrame(295,304,306)
c = c.FreezeFrame(329,334,336)
c = c.FreezeFrame(338,347,349)
c = c.FreezeFrame(353,370,372)
c = c.FreezeFrame(377,378,380)
c = c.FreezeFrame(385,393,395)
c = c.FreezeFrame(397,398,400)
c = c.FreezeFrame(402,446,456)
c = c.FreezeFrame(449,454,456)
c = c.FreezeFrame(459,465,467)
c = c.FreezeFrame(470,471,473)
c = c.FreezeFrame(516,525,527)
c = c.FreezeFrame(530,548,550)
c = c.FreezeFrame(560,577,579)
c

