
LoadPlugin("C:\Users\covec\Videos\vhs\software\Windows\FFmpeg-QTGMC Easy 2025.01.11/ffms2.dll")
FFmpegSource2("C:\Users\covec\Videos\vhs\tmp\vhs_tuner_extracts\callahan_01_archive__1995_jim_linda_wedding_12_reception_ring_close_ups_march_18_1995__35743_36052__clean\extracted.mkv", atrack=-1)
chapter_start_frame = 35743
chapter_end_frame = 36052
c = last
c = c.FreezeFrame(32,32,35)
c = c.FreezeFrame(148,152,154)
c = c.FreezeFrame(161,162,164)
c = c.FreezeFrame(291,294,296)
c = c.FreezeFrame(301,308,299)
c

