#!/usr/bin/env python3.11
"""
Auto-generated by vhs_tuner.py
# Threshold: hard value 2.5000
"""

from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).parent.parent.resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from tracking_loss import TrackingLossConfig, run_tracking_loss_classification

config = TrackingLossConfig(
    archive               = "callahan_01_archive",
    video                 = r"C:\Users\covec\Videos\vhs\..\Archive\callahan_01_archive_proxy.mp4",
    weight_chroma         = 0.35,
    weight_noise          = 0.42,
    weight_tear           = 0.25,
    weight_wave           = 0.25,
    iqr_mult              = 3.5,
    threshold_window_size = 1000,
    crop_top              = 50,
    crop_bottom           = 50,
    crop_left             = 50,
    crop_right            = 50,
    export_review_png_count = 500,
)

if __name__ == "__main__":
    result = run_tracking_loss_classification(config=config)
    print("\nDone.")
    print(f"  Bad frame ranges : {result['badframes_path']}")
    print(f"  Frame scores     : {result['frame_scores_path']}")
    print(f"  Summary          : {result['summary_path']}")
