
LoadPlugin("C:\Users\covec\Videos\vhs\software\Windows\FFmpeg-QTGMC Easy 2025.01.11/ffms2.dll")
FFmpegSource2("C:\Users\covec\Videos\vhs\tmp\vhs_tuner_extracts\callahan_01_archive__1995_jim_linda_wedding_10_rice_toss_send_off_march_18_1995__30870_32218__clean\extracted.mkv", atrack=-1)
chapter_start_frame = 30870
chapter_end_frame = 32218
c = last
c = c.FreezeFrame(136,140,142)
c = c.FreezeFrame(152,152,155)
c = c.FreezeFrame(215,216,218)
c = c.FreezeFrame(461,468,470)
c = c.FreezeFrame(814,822,824)
c = c.FreezeFrame(828,837,839)
c = c.FreezeFrame(864,868,870)
c = c.FreezeFrame(911,934,936)
c = c.FreezeFrame(946,950,952)
c = c.FreezeFrame(957,980,982)
c = c.FreezeFrame(990,995,997)
c = c.FreezeFrame(1001,1050,1083)
c = c.FreezeFrame(1053,1081,1083)
c = c.FreezeFrame(1268,1272,1274)
c = c.FreezeFrame(1301,1311,1313)
c

